{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd\n",
    "import datetime\n",
    "import time\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from webdriver_manager.chrome import ChromeDriverManager\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "import telegram\n",
    "from telegram import Bot\n",
    "import asyncio\n",
    "import schedule\n",
    "\n",
    "current_time = datetime.datetime.now()\n",
    "print(f\"현재 시스템 시간: {current_time}\")\n",
    "\n",
    "\n",
    "# Signal.bz 뉴스 페이지에서 실시간 검색어 10가지를 가져오기\n",
    "URL = \"https://signal.bz/news\"\n",
    "\n",
    "# 텔레그램 설정\n",
    "API_TOKEN = '7936899167:AAFl_3jTqQ-B2b4CUPaKnf_4tWgoY1FI_os'\n",
    "CHAT_ID = '1059657134'\n",
    "\n",
    "# 실시간 검색어 가져오기 함수 (Selenium 사용)\n",
    "def get_realtime_search_terms(url):\n",
    "    print(f\"[{datetime.datetime.now()}] 실시간 검색어 수집을 시작합니다.\")\n",
    "    try:\n",
    "        chrome_options = Options()\n",
    "        chrome_options.add_argument(\"--headless\")\n",
    "        service = Service(ChromeDriverManager().install())\n",
    "        driver = webdriver.Chrome(service=service, options=chrome_options)\n",
    "        \n",
    "        driver.get(url)\n",
    "        print(\"웹페이지에 접속했습니다.\")\n",
    "        \n",
    "        search_elements = driver.find_elements(By.XPATH, \"/html/body/div[1]/div/main/div/section/div/section/section[1]/div[2]/div/div/div/a/span[2]\")\n",
    "        terms = [element.text.strip() for element in search_elements[:10]]\n",
    "        \n",
    "        driver.quit()\n",
    "        if terms:\n",
    "            print(f\"[{datetime.datetime.now()}] 실시간 검색어 수집 성공: {terms}\")\n",
    "        else:\n",
    "            print(f\"[{datetime.datetime.now()}] 실시간 검색어를 수집하지 못했습니다.\")\n",
    "        return terms\n",
    "    except Exception as e:\n",
    "        print(f\"[{datetime.datetime.now()}] 실시간 검색어 수집 중 오류 발생: {e}\")\n",
    "        return []\n",
    "\n",
    "# 인기 뉴스 가져오기 함수 (Selenium 사용)\n",
    "def get_popular_news(url):\n",
    "    print(f\"[{datetime.datetime.now()}] 인기 뉴스 수집을 시작합니다.\")\n",
    "    try:\n",
    "        chrome_options = Options()\n",
    "        chrome_options.add_argument(\"--headless\")\n",
    "        service = Service(ChromeDriverManager().install())\n",
    "        driver = webdriver.Chrome(service=service, options=chrome_options)\n",
    "        \n",
    "        driver.get(url)\n",
    "        print(\"웹페이지에 접속했습니다.\")\n",
    "        \n",
    "        popular_news_elements = driver.find_elements(By.XPATH, \"/html/body/div[1]/div/main/div/section/div/section/section[3]/div/section/div/div/div/div[2]\")\n",
    "        popular_news = [element.text.strip() for element in popular_news_elements[:10]]\n",
    "        \n",
    "        driver.quit()\n",
    "        if popular_news:\n",
    "            print(f\"[{datetime.datetime.now()}] 인기 뉴스 수집 성공: {popular_news}\")\n",
    "        else:\n",
    "            print(f\"[{datetime.datetime.now()}] 인기 뉴스를 수집하지 못했습니다.\")\n",
    "        return popular_news\n",
    "    except Exception as e:\n",
    "        print(f\"[{datetime.datetime.now()}] 인기 뉴스 수집 중 오류 발생: {e}\")\n",
    "        return []\n",
    "\n",
    "# 검색어 출력 및 저장 함수\n",
    "def save_search_terms(terms, popular_news):\n",
    "    print(f\"[{datetime.datetime.now()}] 검색어 및 인기 뉴스 저장을 시작합니다.\")\n",
    "    if terms:\n",
    "        df = pd.DataFrame(terms, columns=['실시간 검색어'])\n",
    "        current_date = datetime.datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "        filename = f\"실검top10_{current_date}.csv\"\n",
    "        df.to_csv(filename, index=False, encoding='utf-8-sig')\n",
    "        print(f\"검색어가 파일로 저장되었습니다: {filename}\")\n",
    "    else:\n",
    "        print(\"검색어를 가져올 수 없습니다.\")\n",
    "    \n",
    "    if popular_news:\n",
    "        df_popular = pd.DataFrame(popular_news, columns=['인기 뉴스'])\n",
    "        filename_popular = f\"인기뉴스_{current_date}.csv\"\n",
    "        df_popular.to_csv(filename_popular, index=False, encoding='utf-8-sig')\n",
    "        print(f\"인기 뉴스가 파일로 저장되었습니다: {filename_popular}\")\n",
    "    else:\n",
    "        print(\"인기 뉴스를 가져올 수 없습니다.\")\n",
    "\n",
    "# 텔레그램으로 메시지 전송 함수\n",
    "async def send_message(api_token, chat_id, message):\n",
    "    print(f\"[{datetime.datetime.now()}] 텔레그램 메시지 전송을 시작합니다.\")\n",
    "    bot = Bot(token=api_token)\n",
    "    try:\n",
    "        await bot.send_message(chat_id=chat_id, text=message)\n",
    "        print(f\"[{datetime.datetime.now()}] 메시지가 성공적으로 전송되었습니다.\")\n",
    "    except telegram.error.TelegramError as e:\n",
    "        print(f\"[{datetime.datetime.now()}] 메시지 전송 실패: {e}\")\n",
    "\n",
    "# 주기적으로 실행하는 함수\n",
    "def job():\n",
    "    print(f\"[{datetime.datetime.now()}] 주기적 작업 실행 시작\")\n",
    "    current_hour = datetime.datetime.now().hour\n",
    "    if current_hour >= 1 or current_hour < 9:\n",
    "        print(f\"[{datetime.datetime.now()}] 현재는 메시지를 보내지 않는 시간입니다.\")\n",
    "        return\n",
    "    \n",
    "    realtime_terms = get_realtime_search_terms(URL)\n",
    "    popular_news = get_popular_news(URL)\n",
    "    save_search_terms(realtime_terms, popular_news)\n",
    "    \n",
    "    loop = asyncio.get_event_loop()\n",
    "    \n",
    "    if realtime_terms:\n",
    "        message = \"실시간 검색어:\\n\" + \"\\n\".join(realtime_terms)\n",
    "        loop.run_until_complete(send_message(API_TOKEN, CHAT_ID, message))\n",
    "    \n",
    "    if popular_news:\n",
    "        message = \"인기 뉴스:\\n\" + \"\\n\".join(popular_news)\n",
    "        loop.run_until_complete(send_message(API_TOKEN, CHAT_ID, message))\n",
    "\n",
    "# 스케줄 설정 - 테스트를 위해 5분마다 실행\n",
    "schedule.every(5).minutes.do(job)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    while True:\n",
    "        print(f\"[{datetime.datetime.now()}] 스케줄 확인 중...\")\n",
    "        schedule.run_pending()\n",
    "        time.sleep(60)  # 1분마다 스케줄 확인\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
